version: '3'

networks:
  laravel:


services:
  nginx:
    image: nginx
    container_name: nginx-app2
    ports:
      - "8081:80"
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html

      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

    networks:
      - laravel


  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-app2
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: notproduction
      MYSQL_PASSWORD: notproduction
      MYSQL_ROOT_PASSWORD: notproduction
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: ./mysql
        target: /var/lib/mysql

    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app2
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html

    ports:
      - "8998:9000"
    networks:
      - laravel

volumes:
  mysql:
  php:
  nginx:
